sudo: required
dist: xenial
language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-mingw-w64-x86-64 ocl-icd-libopencl1 opencl-headers
  - sudo ./scripts/travis_install_intel_opencl.sh

script:
  - make TRAVIS_BUILD=1 && travis_wait make tests
  - make clean; ./make_windows.sh
